variables:
  IMAGE_NAME: nodered
  # VERSION: ""
  REGISTRY_IMAGE: $HARBOR_HOST/$HARBOR_PROJECT/$IMAGE_NAME
  BUILDER_IMAGE: "${IMAGE_NAME}-builder-$CI_CONCURRENT_ID"

image: docker:$DOCKER_VERSION

stages:
  - linting
  - build

before_script:
  - docker login -u $HARBOR_USERNAME -p $HARBOR_PASSWORD $HARBOR_HOST
  # - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker run --privileged --rm tonistiigi/binfmt --install all
  - docker buildx create --use --bootstrap --name ${BUILDER_IMAGE} --config=buildkitd.toml
  - cd docker-custom

after_script:
  - docker buildx stop ${BUILDER_IMAGE}
  - docker buildx rm ${BUILDER_IMAGE}

buildkit_toml:
  stage: .pre
  image: alpine
  before_script: []
  after_script: []
  script:
    - apk add envsubst
    - envsubst < buildkitd.toml.tmpl > buildkitd.toml
  artifacts:
    paths:
      - buildkitd.toml

.hadolint:
  stage: linting
  image: registry.gitlab.com/pipeline-components/hadolint:latest
  script:
    - hadolint Dockerfile
  allow_failure: true
  # rules:
  #   - changes:
  #     - docker-custom/Dockerfile*
  # when: manual

build_publish:
  stage: build
  script:
    # - docker buildx create --use --name ${BUILDER_IMAGE} --config=buildkitd.toml
    - >
      export VERSION=$(sed -rn 's/^\s*\"node-red\": \"([0-9]+\.[0-9]+\.[0-9]+)\"\s*,/\1/p' package.json)
    - echo $VERSION
    - docker buildx bake --push --file package_bake.hcl --progress plain
  # rules:
  #   - changes:
  #       - Dockerfile
  #       - .gitlab-ci.yml
  #       - package_bake.hcl

# publish_image:
#   stage: publish
#   script:
#     - docker push ${REGISTRY_IMAGE}:${VERSION}
#     # - docker push ${REGISTRY_IMAGE}:${VERSION}-armv7
#     # - docker push ${REGISTRY_IMAGE}:${VERSION}-arm64
#     # - docker manifest create ${REGISTRY_IMAGE}:${VERSION} --amend ${REGISTRY_IMAGE}:${VERSION}-armv7 --amend ${REGISTRY_IMAGE}:${VERSION}-arm64
#     # - docker manifest push $REGISTRY_IMAGE:$VERSION
#   rules:
#     - changes:
#         - Dockerfile
#         - .gitlab-ci.yml
#         - package_bake.hcl
